python3 main.py --label_dir=/labels_gt/ --sequence=00
python3 main.py --label_dir=/labels_gt/ --sequence=01
python3 main.py --label_dir=/labels_gt/ --sequence=02
python3 main.py --label_dir=/labels_gt/ --sequence=03
python3 main.py --label_dir=/labels_gt/ --sequence=04
python3 main.py --label_dir=/labels_gt/ --sequence=05
python3 main.py --label_dir=/labels_gt/ --sequence=06
python3 main.py --label_dir=/labels_gt/ --sequence=07
python3 main.py --label_dir=/labels_gt/ --sequence=08
python3 main.py --label_dir=/labels_gt/ --sequence=09
python3 main.py --label_dir=/labels_gt/ --sequence=10
python3 main.py --label_dir=/labels_gt/ --sequence=11
python3 main.py --label_dir=/labels_gt/ --sequence=12
python3 main.py --label_dir=/labels_gt/ --sequence=13
python3 main.py --label_dir=/labels_gt/ --sequence=14
python3 main.py --label_dir=/labels_gt/ --sequence=15
python3 main.py --label_dir=/labels_gt/ --sequence=16
python3 main.py --label_dir=/labels_gt/ --sequence=17
python3 main.py --label_dir=/labels_gt/ --sequence=18
python3 main.py --label_dir=/labels_gt/ --sequence=19
python3 main.py --label_dir=/labels_gt/ --sequence=20
python3 main.py --label_dir=/labels_gt/ --sequence=21
